before_script:
  - yarn install

cache:
  key: $CI_PROJECT_ID
  policy: pull
  untracked: true

install:
  stage: install
  script: echo 'Warming the cache'
  cache:
    key: $CI_PROJECT_ID
    policy: pull-push
    paths:
      - .yarn
      - node_modules
      - 'packages/*/node_modules'

lint:
  stage: test
  script: yarn run lint:all