stages:
  - build

#---------------------------------------------------front build------------------------------------------------

build front:
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - master
  when: manual
